export enum QueryKeys {
  GetInspection = 'GetInspection',
  GetUser = 'GetUser',
  GetBasicDataUser = 'GetBasicDataUser',
  GetInspector = 'GetInspector',
  GetRegenerator = 'GetRegenerator',
  GetDeveloper = 'GetDeveloper',
  GetReport = 'GetReport',
  GetResearcher = 'GetResearcher',
  GetResearch = 'GetResearch',
  GetContributor = 'GetContributor',
  GetContribution = 'GetContribution',
  ProjectDescription = 'ProjectDescription',
  Coordinates = 'Coordinates',
  Invitation = 'Invitation',
  UserDelations = 'UserDelations',
  UserInspections = 'UserInspections',
  GetOffset = 'GetOffset',
  ApprovedTokens = 'ApprovedTokens',
  GetBalance = 'GetBalance'
}