# Resolve react_native_pods.rb with node to allow for hoisting
def node_require(script)
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

# React Native 0.80.2 requirements often trigger 15.1 minimums in modern Xcode
platform :ios, '15.1'
prepare_react_native_project!

# Setup permissions for react-native-permissions
setup_permissions([
  'Camera',
  'LocationAccuracy',
  'LocationAlways',
  'LocationWhenInUse',
])

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'RegenerationCredit' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  pre_install do |installer|
    # This loop runs during the pod resolution phase to bypass the deployment target error
    installer.pod_targets.each do |pod|
      if pod.respond_to?(:platform_name) && pod.platform_name == :ios
        pod.instance_variable_set(:@deployment_target, '15.1')
      end
    end
    $RNMapboxMaps.pre_install(installer)
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )

    $RNMapboxMaps.post_install(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        
        # 1. Standardize everything to iOS 15.1
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'

        # 2. Fix for 'fmt' library (Xcode 16/26 C++20 fix)
        if target.name.include?('fmt')
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'FMT_USE_CONSTEVAL=0']
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        end

        # 3. Resolve Hermes/React-hermes header issues
        config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)', '$(PODS_ROOT)/Headers/Public/React-hermes']
        
        # 4. General modern Xcode settings
        config.build_settings['ENABLE_BITCODE'] = 'NO'
      end
    end
  end
end